import createClient from 'openapi-fetch';
// Generated by `pnpm api:generate` (needs the api running on :8080).
import type { paths } from './schema';

export const api = createClient<paths>({ baseUrl: '/' });
