-- Lifestyle > Fitness > Nutrition (backend package/schema stay "logbook", like the other Lifestyle modules).

-- One row per user: their daily calorie limit.
CREATE TABLE logbook.nutrition_goal (
    user_id    bigint      PRIMARY KEY REFERENCES core.app_user (id) ON DELETE CASCADE,
    daily_kcal integer     NOT NULL CHECK (daily_kcal BETWEEN 500 AND 20000),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- The user's own food library: kcal per 100 g, plus an optional "one portion" size. Foods found through Open Food
-- Facts are copied in here once picked, so day-to-day use never depends on the online service.
CREATE TABLE logbook.food (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint           NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    name          varchar(200)     NOT NULL,
    brand         varchar(200),
    kcal_per_100g double precision NOT NULL CHECK (kcal_per_100g >= 0 AND kcal_per_100g <= 1000),
    portion_grams double precision CHECK (portion_grams > 0),
    portion_label varchar(60),
    barcode       varchar(32),
    source        varchar(20)      NOT NULL DEFAULT 'MANUAL' CHECK (source IN ('MANUAL', 'OPEN_FOOD_FACTS')),
    last_grams    double precision, -- the amount used last time, to prefill the next one
    use_count     integer          NOT NULL DEFAULT 0,
    last_used_at  timestamptz,
    created_at    timestamptz      NOT NULL DEFAULT now()
);

CREATE INDEX food_user_idx ON logbook.food (user_id, last_used_at DESC);
CREATE UNIQUE INDEX food_user_barcode_uq ON logbook.food (user_id, barcode) WHERE barcode IS NOT NULL;

-- What was eaten and when. name/kcal are snapshots, so editing or deleting a food later never rewrites history
-- (food_id just goes null if the food is deleted). `day` is the calendar day as the user saw it when logging,
-- which avoids server-side time zone guesswork for "today".
CREATE TABLE logbook.meal_entry (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint           NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    day        date             NOT NULL,
    eaten_at   timestamptz      NOT NULL,
    food_id    bigint           REFERENCES logbook.food (id) ON DELETE SET NULL,
    name       varchar(200)     NOT NULL,
    grams      double precision,
    kcal       integer          NOT NULL CHECK (kcal BETWEEN 0 AND 20000),
    created_at timestamptz      NOT NULL DEFAULT now()
);

CREATE INDEX meal_entry_user_day_idx ON logbook.meal_entry (user_id, day, eaten_at);
