-- Lifestyle > Routine (backend package/schema stay "logbook", like the other Lifestyle modules).

-- A recurring thing to do. DAILY = every day. WEEKLY = times_per_week times in a Monday-Sunday week, on whichever
-- days suit. target_minutes is optional: a routine is either just checked off, or has a time ("meditate, 10 min").
CREATE TABLE logbook.routine (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    name           varchar(200) NOT NULL,
    note           varchar(500),
    frequency      varchar(10)  NOT NULL CHECK (frequency IN ('DAILY', 'WEEKLY')),
    times_per_week integer      NOT NULL DEFAULT 1 CHECK (times_per_week BETWEEN 1 AND 7),
    target_minutes integer CHECK (target_minutes BETWEEN 1 AND 1440),
    created_at     timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX routine_user_idx ON logbook.routine (user_id, id);

-- One row = "done on this day" (at most once per routine per day, so a 3x-a-week routine means three different
-- days). minutes is what was actually spent, for routines that have a time.
CREATE TABLE logbook.routine_completion (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    routine_id bigint      NOT NULL REFERENCES logbook.routine (id) ON DELETE CASCADE,
    day        date        NOT NULL,
    minutes    integer CHECK (minutes BETWEEN 1 AND 1440),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT routine_completion_routine_day_uq UNIQUE (routine_id, day)
);

CREATE INDEX routine_completion_user_day_idx ON logbook.routine_completion (user_id, day);

-- The daily "what is still open" reminder: once per local day, at or after remind_at, in the user's time zone.
CREATE TABLE logbook.routine_reminder_settings (
    user_id      bigint  PRIMARY KEY REFERENCES core.app_user (id) ON DELETE CASCADE,
    enabled      boolean NOT NULL DEFAULT true,
    remind_at    time    NOT NULL DEFAULT '16:00',
    last_sent_on date
);
