CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE core.app_user (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(64)  NOT NULL,
    password_hash   varchar(100) NOT NULL,
    role            varchar(20)  NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    enabled         boolean      NOT NULL DEFAULT true,
    failed_attempts integer      NOT NULL DEFAULT 0,
    locked_until    timestamptz,
    last_login_at   timestamptz,
    created_at      timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX app_user_username_uq ON core.app_user (lower(username));

-- Spring Session JDBC tables. Owned by Flyway from now on (initialize-schema: never).
-- IF NOT EXISTS because earlier versions let Spring create them at startup.
CREATE TABLE IF NOT EXISTS spring_session (
    primary_id            char(36) NOT NULL,
    session_id            char(36) NOT NULL,
    creation_time         bigint   NOT NULL,
    last_access_time      bigint   NOT NULL,
    max_inactive_interval int      NOT NULL,
    expiry_time           bigint   NOT NULL,
    principal_name        varchar(100),
    CONSTRAINT spring_session_pk PRIMARY KEY (primary_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS spring_session_ix1 ON spring_session (session_id);
CREATE INDEX IF NOT EXISTS spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX IF NOT EXISTS spring_session_ix3 ON spring_session (principal_name);

CREATE TABLE IF NOT EXISTS spring_session_attributes (
    session_primary_id char(36)     NOT NULL,
    attribute_name     varchar(200) NOT NULL,
    attribute_bytes    bytea        NOT NULL,
    CONSTRAINT spring_session_attributes_pk PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT spring_session_attributes_fk FOREIGN KEY (session_primary_id)
        REFERENCES spring_session (primary_id) ON DELETE CASCADE
);
