-- Gaming > Counter-Strike 2 > Improvement. All rows belong to a user (core.app_user).

-- Marks that the default routine/principles were created for a user (see Cs2ImprovementService.ensureSeeded).
CREATE TABLE gaming.cs2_profile (
    user_id   bigint PRIMARY KEY REFERENCES core.app_user (id) ON DELETE CASCADE,
    seeded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE gaming.cs2_routine_item (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    title          varchar(200) NOT NULL,
    description    text,
    category       varchar(20)  NOT NULL CHECK (category IN ('WARMUP', 'PRACTICE')),
    target_minutes integer CHECK (target_minutes BETWEEN 1 AND 600),
    sort_order     integer      NOT NULL DEFAULT 0,
    active         boolean      NOT NULL DEFAULT true,
    created_at     timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX cs2_routine_item_user_idx ON gaming.cs2_routine_item (user_id, sort_order);

-- A row means "done on that day".
CREATE TABLE gaming.cs2_routine_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint  NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    item_id    bigint  NOT NULL REFERENCES gaming.cs2_routine_item (id) ON DELETE CASCADE,
    log_date   date    NOT NULL,
    minutes    integer CHECK (minutes BETWEEN 1 AND 600),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT cs2_routine_log_item_day_uq UNIQUE (item_id, log_date)
);

CREATE INDEX cs2_routine_log_user_day_idx ON gaming.cs2_routine_log (user_id, log_date DESC);

CREATE TABLE gaming.cs2_session_review (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint  NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    played_on  date    NOT NULL,
    focus      integer NOT NULL CHECK (focus BETWEEN 1 AND 5),
    movement   integer NOT NULL CHECK (movement BETWEEN 1 AND 5),
    utility    integer NOT NULL CHECK (utility BETWEEN 1 AND 5),
    notes      text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX cs2_session_review_user_idx ON gaming.cs2_session_review (user_id, played_on DESC);

CREATE TABLE gaming.cs2_principle (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    title      varchar(200) NOT NULL,
    body       text,
    category   varchar(20)  NOT NULL
        CHECK (category IN ('MINDSET', 'MOVEMENT', 'UTILITY', 'AIM', 'PRACTICE', 'PREPARATION')),
    pinned     boolean      NOT NULL DEFAULT false,
    sort_order integer      NOT NULL DEFAULT 0,
    created_at timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX cs2_principle_user_idx ON gaming.cs2_principle (user_id, sort_order);
