CREATE SCHEMA IF NOT EXISTS logbook;

-- ---- core: notifications (in-app inbox + Web Push devices) ----

CREATE TABLE core.notification (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    title      varchar(200) NOT NULL,
    body       text,
    url        varchar(500),
    category   varchar(40)  NOT NULL DEFAULT 'general',
    created_at timestamptz  NOT NULL DEFAULT now(),
    read_at    timestamptz
);

CREATE INDEX notification_user_idx ON core.notification (user_id, created_at DESC);

CREATE TABLE core.push_subscription (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    endpoint     text         NOT NULL,
    p256dh       varchar(255) NOT NULL,
    auth         varchar(255) NOT NULL,
    user_agent   varchar(255),
    created_at   timestamptz  NOT NULL DEFAULT now(),
    last_used_at timestamptz
);

CREATE UNIQUE INDEX push_subscription_endpoint_uq ON core.push_subscription (endpoint);
CREATE INDEX push_subscription_user_idx ON core.push_subscription (user_id);

-- per-user notification preferences that every module shares (reminders are evaluated in the user's time zone)
CREATE TABLE core.notification_prefs (
    user_id  bigint PRIMARY KEY REFERENCES core.app_user (id) ON DELETE CASCADE,
    timezone varchar(64) NOT NULL DEFAULT 'UTC'
);

-- ---- logbook > todos ----

CREATE TABLE logbook.todo (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    title      varchar(300) NOT NULL,
    note       text,
    due_date   date,
    done       boolean      NOT NULL DEFAULT false,
    done_at    timestamptz,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX todo_user_state_idx ON logbook.todo (user_id, done, due_date);

CREATE TABLE logbook.todo_reminder_settings (
    user_id          bigint PRIMARY KEY REFERENCES core.app_user (id) ON DELETE CASCADE,
    enabled          boolean NOT NULL DEFAULT true,
    remind_at        time    NOT NULL DEFAULT '08:00',
    notify_due_today boolean NOT NULL DEFAULT true,
    notify_overdue   boolean NOT NULL DEFAULT true,
    last_sent_on     date
);
