-- Lifestyle > Shopping List (backend package/schema stay "logbook"; only the frontend nav renamed to "Lifestyle").
CREATE TABLE logbook.shopping_list (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    name         varchar(200) NOT NULL,
    finalized_at timestamptz,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX shopping_list_user_idx ON logbook.shopping_list (user_id, finalized_at, updated_at DESC);

CREATE TABLE logbook.shopping_item (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    list_id    bigint       NOT NULL REFERENCES logbook.shopping_list (id) ON DELETE CASCADE,
    name       varchar(200) NOT NULL,
    quantity   integer CHECK (quantity BETWEEN 1 AND 9999),
    unit       varchar(30),
    checked    boolean      NOT NULL DEFAULT false,
    checked_at timestamptz,
    sort_order integer      NOT NULL DEFAULT 0,
    created_at timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX shopping_item_list_idx ON logbook.shopping_item (list_id, checked, sort_order);

-- Per-user autocomplete pool: upserted every time an item is added to any list, ranked by use_count/last_used_at.
CREATE TABLE logbook.shopping_known_item (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    name          varchar(200) NOT NULL,
    use_count     integer      NOT NULL DEFAULT 1,
    last_used_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX shopping_known_item_user_name_uq ON logbook.shopping_known_item (user_id, lower(name));

-- Recurring templates: a saved, reusable set of items. "Use" a template to create a fresh list from it.
CREATE TABLE logbook.shopping_template (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    name       varchar(200) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX shopping_template_user_idx ON logbook.shopping_template (user_id, updated_at DESC);

CREATE TABLE logbook.shopping_template_item (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    template_id bigint       NOT NULL REFERENCES logbook.shopping_template (id) ON DELETE CASCADE,
    name        varchar(200) NOT NULL,
    quantity    integer CHECK (quantity BETWEEN 1 AND 9999),
    unit        varchar(30),
    sort_order  integer      NOT NULL DEFAULT 0
);

CREATE INDEX shopping_template_item_template_idx ON logbook.shopping_template_item (template_id, sort_order);
