-- Gaming > Counter-Strike 2 > Analysis. Per-.dem-upload data, private to the uploading user. The raw .dem file
-- itself lives on disk (basecamp.analysis.demo-storage-dir), not in the database, and is deleted after a
-- successful parse; only the extracted data below is kept.
CREATE TABLE gaming.cs2_demo (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint       NOT NULL REFERENCES core.app_user (id) ON DELETE CASCADE,
    original_filename varchar(255) NOT NULL,
    map               varchar(64),
    size_bytes        bigint       NOT NULL,
    status            varchar(20)  NOT NULL DEFAULT 'UPLOADED'
        CHECK (status IN ('UPLOADED', 'PARSING', 'READY', 'FAILED')),
    error_message     text,
    uploaded_at       timestamptz  NOT NULL DEFAULT now(),
    parsed_at         timestamptz
);

CREATE INDEX cs2_demo_user_idx ON gaming.cs2_demo (user_id, uploaded_at DESC);

CREATE TABLE gaming.cs2_demo_round (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_id     bigint      NOT NULL REFERENCES gaming.cs2_demo (id) ON DELETE CASCADE,
    round_number integer    NOT NULL,
    winner_team varchar(4), -- "CT", "T" or null (tie / no winner)
    ct_score    integer     NOT NULL,
    t_score     integer     NOT NULL
);

CREATE INDEX cs2_demo_round_demo_idx ON gaming.cs2_demo_round (demo_id, round_number);

CREATE TABLE gaming.cs2_demo_kill (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_id           bigint      NOT NULL REFERENCES gaming.cs2_demo (id) ON DELETE CASCADE,
    round_number      integer     NOT NULL,
    tick              integer     NOT NULL,
    attacker_steam_id varchar(20),
    attacker_name     varchar(64),
    attacker_team     varchar(4),
    attacker_x        double precision,
    attacker_y        double precision,
    attacker_z        double precision,
    victim_steam_id   varchar(20),
    victim_name       varchar(64),
    victim_team       varchar(4),
    victim_x          double precision NOT NULL,
    victim_y          double precision NOT NULL,
    victim_z          double precision NOT NULL,
    weapon            varchar(64) NOT NULL,
    headshot          boolean     NOT NULL,
    wallbang          boolean     NOT NULL
);

CREATE INDEX cs2_demo_kill_demo_idx ON gaming.cs2_demo_kill (demo_id, round_number);

CREATE TABLE gaming.cs2_demo_grenade (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_id           bigint      NOT NULL REFERENCES gaming.cs2_demo (id) ON DELETE CASCADE,
    round_number      integer     NOT NULL,
    type              varchar(20) NOT NULL, -- Flash, Smoke, HE, Molotov, Incendiary, Decoy
    thrower_steam_id  varchar(20),
    thrower_name      varchar(64),
    thrower_team      varchar(4),
    detonate_x        double precision,
    detonate_y        double precision,
    detonate_z        double precision,
    trajectory        text        NOT NULL DEFAULT '[]' -- JSON [{x,y,z}, ...]; the flight path, for the future animated replay
);

CREATE INDEX cs2_demo_grenade_demo_idx ON gaming.cs2_demo_grenade (demo_id, round_number);

-- Periodic (see analysis-parser's sample interval) player position snapshots. Powers both today's static
-- heatmaps (aggregate across a demo/round) and a future animated replay (ordered by tick).
CREATE TABLE gaming.cs2_demo_position (
    id       bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_id  bigint      NOT NULL REFERENCES gaming.cs2_demo (id) ON DELETE CASCADE,
    round_number integer NOT NULL,
    tick     integer     NOT NULL,
    steam_id varchar(20) NOT NULL,
    name     varchar(64) NOT NULL,
    team     varchar(4)  NOT NULL,
    x        double precision NOT NULL,
    y        double precision NOT NULL,
    z        double precision NOT NULL,
    health   integer     NOT NULL,
    alive    boolean     NOT NULL
);

CREATE INDEX cs2_demo_position_demo_round_idx ON gaming.cs2_demo_position (demo_id, round_number, tick);
